language: node_js
node_js:
  - "10.13.0"
cache:
  directories:
  - "node_modules"
services:
  - mongodb
env:
    - NODE_ENV=travisci
before_script:
  - cd server
  - npm cache clean --force
  - npm install
script:
  - npm test

